- name: variables to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am leaning DevOPS with AWS, Duration is: 120HRS, Trainer: Sivakumar Reddy"