- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar Reddy"

  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am leaning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the information
    Vars:
      Course: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am leaning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the information again
    ansible.builtin.debug:
      msg: "Hi, I am leaning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"   